import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/shared/sidebar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("h-full", "antialiased", poppins.className, "font-sans", geist.variable)}>
      <body className="flex h-screen min-h-0 flex-row overflow-hidden">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Sidebar />
          <main className="relative z-0 min-h-0 min-w-0 flex-1 overflow-y-auto bg-slate-50 p-8 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
